name: "Docker Build and Push"
description: "Reusable action to build and push Docker images"
inputs:
  service-name:
    description: "Name of the service (api, bot, lockdex)"
    required: true
  docker-username:
    description: "Docker Hub username"
    required: true
  docker-password:
    description: "Docker Hub password"
    required: true
  node-version:
    description: "Node.js version to use"
    required: false
    default: "22.11.0"

outputs:
  version:
    description: "Version of the service from package.json"
    value: ${{ steps.get-version.outputs.version }}
  image-name:
    description: "Full Docker image name with tag"
    value: ${{ steps.build-push.outputs.imageid }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache-dependency-path: pnpm-lock.yaml

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Install dependencies
      working-directory: ./apps/${{ inputs.service-name }}
      run: pnpm install
      shell: bash

    - name: Read version from package.json
      id: get-version
      working-directory: ./apps/${{ inputs.service-name }}
      run: |
        VERSION=$(jq -r '.version' package.json)
        echo "Current version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      shell: bash

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: stormix/deadlock-mods-${{ inputs.service-name }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      id: build-push
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
        file: ./apps/${{ inputs.service-name }}/Dockerfile
        push: true
        tags: |
          ${{ inputs.docker-username }}/deadlock-mods-${{ inputs.service-name }}:${{ steps.get-version.outputs.version }}
          ${{ inputs.docker-username }}/deadlock-mods-${{ inputs.service-name }}:latest
        labels: ${{ steps.meta.outputs.labels }}
