name: Publish API Docker image
env:
  NODE_VERSION: "22.11.0"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/api/**"
      - "packages/**"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Build and push Docker image
        id: docker-build
        uses: ./.github/actions/docker-build-push
        with:
          service-name: api
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          node-version: ${{ env.NODE_VERSION }}

      # - name: Restart Kubernetes deployment
      #   uses: ./.github/actions/k8s-restart-deployment
      #   with:
      #     service-name: api
      #     kubeconfig: ${{ secrets.KUBECONFIG }}
      #     namespace: ${{ secrets.K8S_NAMESPACE || 'default' }}
